version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  stackhawk: stackhawk/stackhawk@1.0.2

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

workflows:
  scan-remote:
    jobs:
      - stackhawk/hawkscan-remote:
          configuration-files: stackhawk.yml
          host: 'http://example.com'
